Repository microsoftgraph/entra-powershell, pull requests merged in 2025-01, with the labels that each got.

#1246 Enhancement: Get-EntraContext - Add Entra PowerShell version to response
  module/Entra/AdditionalFunctions/Get-EntraContext.ps1
  module/EntraBeta/AdditionalFunctions/Get-EntraContext.ps1
Labels: Ready For Review, P0

#1235 Update Module Description to reflect new naming
  module/Entra/config/ModuleMetadata.json
  module/EntraBeta/config/ModuleMetadata.json
  src/EntraModuleBuilder.ps1
Labels: Ready For Review, P0

#1251 Hotfix - Update-EntraBetaUserAuthenticationRequirement
  module/EntraBeta/AdditionalFunctions/Update-EntraBetaUserAuthenticationRequirement.ps1
Labels: Ready For Review, P0

#1252 Suppress source files
  src/CompatibilityAdapterBuilder.ps1
Labels: Ready For Review, P0

#1276 [Modularize] Hot fix - New-EntraBetaPrivateAccessApplicationSegment
  module/docs/entra-powershell-beta/NetworkAccess/New-EntraBetaPrivateAccessApplicationSegment.md
Labels: Ready For Review, P0

#1282 [Modularize] Hotfix - Array list fix for RequiredResourceAccess - Set-EntraApplication
  module/Entra/Microsoft.Entra/Applications/Set-EntraApplication.ps1
  module/EntraBeta/Microsoft.Entra.Beta/Applications/Set-EntraBetaApplication.ps1
Labels: P0

#1283 [Modularize] Enhancement: Get-EntraContext - Add Entra PowerShell version to response
  module/Entra/Microsoft.Entra/Authentication/Get-EntraContext.ps1
  module/EntraBeta/Microsoft.Entra.Beta/Authentication/Get-EntraContext.ps1
  src/EntraAliasDefinitions.ps1
  src/EntraBetaAliasDefinitions.ps1
Labels: P0

#1284 [Modularize] Hotfix - Update-EntraBetaUserAuthenticationRequirement
  module/EntraBeta/Microsoft.Entra.Beta/SignIns/Update-EntraBetaUserAuthenticationRequirement.ps1
  test/EntraBeta/SignIns/Update-EntraBetaUserAuthenticationRequirement.Tests.ps1
Labels: P0

#1272 [Modularize] Enhancement - Connect-Entra as a proxy function
  module/Entra/Microsoft.Entra/Authentication/Connect-Entra.ps1
  module/EntraBeta/Microsoft.Entra.Beta/Authentication/Connect-Entra.ps1
  test/Entra/Authentication/Connect-Entra.Tests.ps1
Labels: Ready For Review, P0

#1288 [Modularize] Example quality bump batch 4
  module/docs/entra-powershell-beta/DirectoryManagement/Add-EntraBetaDirectoryRoleMember.md
  module/docs/entra-powershell-beta/DirectoryManagement/Enable-EntraBetaDirectoryRole.md
  module/docs/entra-powershell-beta/DirectoryManagement/Get-EntraBetaDirectoryObjectOnPremisesProvisioningError.md
  module/docs/entra-powershell-beta/DirectoryManagement/Get-EntraBetaDirectoryRole.md
  module/docs/entra-powershell-beta/DirectoryManagement/Get-EntraBetaDirectoryRoleMember.md
  module/docs/entra-powershell-beta/DirectoryManagement/Get-EntraBetaDirectoryRoleTemplate.md
  module/docs/entra-powershell-beta/DirectoryManagement/Remove-EntraBetaDirectoryRoleMember.md
  module/docs/entra-powershell-beta/DirectoryManagement/Restore-EntraBetaDeletedDirectoryObject.md
  module/docs/entra-powershell-beta/DirectoryManagement/Set-EntraBetaDirSyncConfiguration.md
  module/docs/entra-powershell-beta/DirectoryManagement/Set-EntraBetaDirSyncEnabled.md
  module/docs/entra-powershell-beta/DirectoryManagement/Set-EntraBetaDirSyncFeature.md
  module/docs/entra-powershell-beta/Governance/Get-EntraBetaDirectoryRoleDefinition.md
  module/docs/entra-powershell-beta/Governance/New-EntraBetaDirectoryRoleDefinition.md
  module/docs/entra-powershell-beta/Governance/Set-EntraBetaDirectoryRoleDefinition.md
  module/docs/entra-powershell-beta/Groups/Remove-EntraBetaObjectSetting.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Add-EntraDirectoryRoleMember.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Enable-EntraDirectoryRole.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Get-EntraDirectoryObjectOnPremisesProvisioningError.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Get-EntraDirectoryRole.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Get-EntraDirectoryRoleMember.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Get-EntraDirectoryRoleTemplate.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Remove-EntraDirectoryRoleMember.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Restore-EntraDeletedDirectoryObject.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Set-EntraDirSyncConfiguration.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Set-EntraDirSyncEnabled.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Set-EntraDirSyncFeature.md
  module/docs/entra-powershell-v1.0/Governance/Get-EntraDirectoryRoleDefinition.md
  module/docs/entra-powershell-v1.0/Governance/New-EntraDirectoryRoleDefinition.md
  module/docs/entra-powershell-v1.0/Governance/Set-EntraDirectoryRoleDefinition.md
Labels: Ready For Review, P0

#1268 [Modularize] - Get-EntraUserGroup
  module/Entra/Microsoft.Entra/Users/Get-EntraUserGroup.ps1
  module/EntraBeta/Microsoft.Entra.Beta/Users/Get-EntraBetaUserGroup.ps1
  module/docs/entra-powershell-beta/Users/Get-EntraBetaUserGroup.md
  module/docs/entra-powershell-v1.0/Users/Get-EntraUserGroup.md
  test/Entra/Users/Get-EntraUserGroup.Tests.ps1
  test/EntraBeta/Users/Get-EntraBetaUserGroup.Tests.ps1
Labels: Ready For Review, P1

#1270 [Modularize] Set-EntraAdministrativeUnit improvements (adding additional properties)
  module/Entra/Microsoft.Entra/DirectoryManagement/Set-EntraAdministrativeUnit.ps1
  module/EntraBeta/Microsoft.Entra.Beta/DirectoryManagement/Set-EntraBetaAdministrativeUnit.ps1
  module/docs/entra-powershell-beta/DirectoryManagement/Set-EntraBetaAdministrativeUnit.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Set-EntraAdministrativeUnit.md
  test/Entra/DirectoryManagement/Set-EntraAdministrativeUnit.Tests.ps1
  test/EntraBeta/DirectoryManagement/Set-EntraBetaAdministrativeUnit.Tests.ps1
Labels: Ready For Review, P1

#1291 Added -Property example to docs for Get-EntraGroup
  module/docs/entra-powershell-beta/Groups/Get-EntraBetaGroup.md
  module/docs/entra-powershell-v1.0/Groups/Get-EntraGroup.md
Labels: Ready For Review, P0

#1281 [Modularize] Get-EntraDeletedServicePrincipal
  module/Entra/Microsoft.Entra/Applications/Get-EntraDeletedServicePrincipal.ps1
  module/EntraBeta/Microsoft.Entra.Beta/Applications/Get-EntraBetaDeletedServicePrincipal.ps1
  module/docs/entra-powershell-beta/Applications/Get-EntraBetaDeletedServicePrincipal.md
  module/docs/entra-powershell-v1.0/Applications/Get-EntraDeletedServicePrincipal.md
  test/Entra/Applications/Get-EntraDeletedServicePrincipal.Tests.ps1
  test/EntraBeta/Applications/Get-EntraBetaDeletedServicePrincipal.Tests.ps1
Labels: Ready For Review, P1

#1280 [Modularize] Get-EntraDeletedUser
  module/Entra/Microsoft.Entra/Users/Get-EntraDeletedUser.ps1
  module/EntraBeta/Microsoft.Entra.Beta/Users/Get-EntraBetaDeletedUser.ps1
  module/docs/entra-powershell-beta/Users/Get-EntraBetaDeletedUser.md
  module/docs/entra-powershell-v1.0/Users/Get-EntraDeletedUser.md
  test/Entra/Users/Get-EntraDeletedUser.Tests.ps1
  test/EntraBeta/Users/Get-EntraBetaDeletedUser.Tests.ps1
Labels: Ready For Review, P1

#1279 [Modularize] Get-EntraDeletedAdministrativeUnit
  module/Entra/Microsoft.Entra/DirectoryManagement/Get-EntraDeletedAdministrativeUnit.ps1
  module/EntraBeta/Microsoft.Entra.Beta/DirectoryManagement/Get-EntraBetaDeletedAdministrativeUnit.ps1
  module/docs/entra-powershell-beta/DirectoryManagement/Get-EntraBetaDeletedAdministrativeUnit.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Get-EntraDeletedAdministrativeUnit.md
  test/Entra/DirectoryManagement/Get-EntraDeletedAdministrativeUnit.Tests.ps1
  test/EntraBeta/DirectoryManagement/Get-EntraBetaDeletedAdministrativeUnit.Tests.ps1
Labels: Ready For Review, P1

#1278 [Modularize] Get-EntraDeletedDevice
  module/Entra/Microsoft.Entra/DirectoryManagement/Get-EntraDeletedDevice.ps1
  module/EntraBeta/Microsoft.Entra.Beta/DirectoryManagement/Get-EntraBetaDeletedDevice.ps1
  module/docs/entra-powershell-beta/DirectoryManagement/Get-EntraBetaDeletedDevice.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Get-EntraDeletedDevice.md
  test/Entra/DirectoryManagement/Get-EntraDeletedDevice.Tests.ps1
  test/EntraBeta/DirectoryManagement/Get-EntraBetaDeletedDevice.Tests.ps1
Labels: Ready For Review, P1

#1271 [Modularize] Get-EntraUserInactiveSignIn
  module/Entra/Microsoft.Entra/Users/Get-EntraUserInactiveSignIn.ps1
  module/EntraBeta/Microsoft.Entra.Beta/Users/Get-EntraBetaUserInactiveSignIn.ps1
  module/docs/entra-powershell-beta/Users/Get-EntraBetaUserInactiveSignIn.md
  module/docs/entra-powershell-v1.0/Users/Get-EntraUserInactiveSignIn.md
  test/Entra/Users/Get-EntraUserInactiveSignIn.Tests.ps1
  test/EntraBeta/Users/Get-EntraBetaUserInactiveSignIn.Tests.ps1
Labels: Ready For Review, P1

#1219 0.20.0 release - Enrich examples to boost example quality KPI - Batch 7
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaAuthorizationPolicy.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaConditionalAccessPolicy.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaFeatureRolloutPolicy.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaNamedLocationPolicy.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaPermissionGrantConditionSet.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaPolicy.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaConditionalAccessPolicy.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaFeatureRolloutPolicy.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaNamedLocationPolicy.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaOauth2PermissionGrant.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaPermissionGrantConditionSet.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaPermissionGrantPolicy.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaPolicy.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Remove-EntraBetaConditionalAccessPolicy.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Remove-EntraBetaFeatureRolloutPolicy.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Remove-EntraBetaNamedLocationPolicy.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Remove-EntraBetaPermissionGrantConditionSet.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Remove-EntraBetaPolicy.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Set-EntraBetaAuthorizationPolicy.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Set-EntraBetaConditionalAccessPolicy.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Set-EntraBetaFeatureRolloutPolicy.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Set-EntraBetaNamedLocationPolicy.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Set-EntraBetaPermissionGrantConditionSet.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Set-EntraBetaPermissionGrantPolicy.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Set-EntraBetaPolicy.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraAuthorizationPolicy.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraConditionalAccessPolicy.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraFeatureRolloutPolicy.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraNamedLocationPolicy.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraPermissionGrantConditionSet.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraPolicy.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraConditionalAccessPolicy.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraFeatureRolloutPolicy.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraNamedLocationPolicy.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraOauth2PermissionGrant.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraPermissionGrantConditionSet.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraPermissionGrantPolicy.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraPolicy.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Remove-EntraConditionalAccessPolicy.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Remove-EntraFeatureRolloutPolicy.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Remove-EntraNamedLocationPolicy.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Remove-EntraPermissionGrantConditionSet.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Remove-EntraPolicy.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Set-EntraAuthorizationPolicy.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Set-EntraConditionalAccessPolicy.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Set-EntraFeatureRolloutPolicy.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Set-EntraNamedLocationPolicy.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Set-EntraPermissionGrantConditionSet.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Set-EntraPermissionGrantPolicy.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Set-EntraPolicy.md
Labels: Ready For Review, P0

#1217 0.20.0 release - Enrich examples to boost example quality KPI - Batch 6
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaAccountSku.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaAuditDirectoryLog.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaDirectoryRoleAssignment.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaDirectoryRoleDefinition.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaIdentityProvider.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaSubscribedSku.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaDirectoryRoleAssignment.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaDirectoryRoleDefinition.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaIdentityProvider.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaInvitation.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaOauth2PermissionGrant.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Remove-EntraBetaDirectoryRoleAssignment.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Remove-EntraBetaDirectoryRoleDefinition.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Remove-EntraBetaIdentityProvider.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Remove-EntraBetaOAuth2PermissionGrant.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Set-EntraBetaDirectoryRoleDefinition.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Set-EntraBetaIdentityProvider.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Set-EntraBetaPartnerInformation.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraAccountSku.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraAuditDirectoryLog.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraDirectoryRoleAssignment.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraDirectoryRoleDefinition.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraIdentityProvider.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraSubscribedSku.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraDirectoryRoleAssignment.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraDirectoryRoleDefinition.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraIdentityProvider.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraInvitation.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraOauth2PermissionGrant.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Remove-EntraDirectoryRoleAssignment.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Remove-EntraDirectoryRoleDefinition.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Remove-EntraIdentityProvider.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Remove-EntraOAuth2PermissionGrant.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Set-EntraDirectoryRoleDefinition.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Set-EntraIdentityProvider.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Set-EntraPartnerInformation.md
Labels: Ready For Review, P0

#1216 0.20.0 release - Enrich examples to boost example quality KPI - Batch 5 [domains]
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaDomainNameReference.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaDomainServiceConfigurationRecord.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaDomainVerificationDnsRecord.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaPasswordPolicy.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaDomain.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Remove-EntraBetaDomain.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Set-EntraBetaDomainFederationSettings.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraDomainNameReference.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraDomainServiceConfigurationRecord.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraDomainVerificationDnsRecord.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraPasswordPolicy.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraDomain.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Remove-EntraDomain.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Set-EntraDomainFederationSettings.md
  module/docs/future/Microsoft.Graph.Entra/Get-CrossCloudVerificationCode.md
Labels: Ready For Review, P0

#1196 0.20.0 release - Enrich examples to boost example quality KPI - Batch 3 [devices]
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Add-EntraBetaDeviceRegisteredOwner.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Add-EntraBetaDeviceRegisteredUser.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaDevice.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaDeviceRegisteredOwner.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaDeviceRegisteredUser.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaDevice.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Remove-EntraBetaDevice.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Remove-EntraBetaDeviceRegisteredOwner.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Remove-EntraBetaDeviceRegisteredUser.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Set-EntraBetaDevice.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Add-EntraDeviceRegisteredOwner.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Add-EntraDeviceRegisteredUser.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraDevice.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraDeviceRegisteredOwner.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraDeviceRegisteredUser.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraDevice.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Remove-EntraDevice.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Remove-EntraDeviceRegisteredOwner.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Remove-EntraDeviceRegisteredUser.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Set-EntraDevice.md
Labels: Ready For Review, P0

#1193 0.20.0 release - Enrich examples to boost example quality KPI - Batch 2
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Add-EntraBetaCustomSecurityAttributeDefinitionAllowedValue.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaContact.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaContactDirectReport.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaContactManager.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaContactMembership.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaCustomSecurityAttributeDefinition.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaCustomSecurityAttributeDefinitionAllowedValue.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaAttributeSet.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaCustomSecurityAttributeDefinition.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Remove-EntraBetaContact.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Set-EntraBetaAttributeSet.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Set-EntraBetaCustomSecurityAttributeDefinition.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Set-EntraBetaCustomSecurityAttributeDefinitionAllowedValue.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Add-EntraCustomSecurityAttributeDefinitionAllowedValue.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Add-EntraEnvironment.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Connect-Entra.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraContact.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraContactDirectReport.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraContactManager.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraContactMembership.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraCustomSecurityAttributeDefinition.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraCustomSecurityAttributeDefinitionAllowedValue.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraAttributeSet.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraCustomSecurityAttributeDefinition.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Remove-EntraContact.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Set-EntraAttributeSet.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Set-EntraCustomSecurityAttributeDefinition.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Set-EntraCustomSecurityAttributeDefinitionAllowedValue.md
Labels: Ready For Review, P0

#1189 0.20.0 release - Enrich examples to boost example quality KPI - Batch 2 (users)
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaUserAppRoleAssignment.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaUserDirectReport.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaUserExtension.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaUserLicenseDetail.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaUserManager.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaUserMembership.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Get-EntraBetaUserOwnedObject.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaUser.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaUserAppRoleAssignment.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Remove-EntraBetaUser.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Remove-EntraBetaUserAppRoleAssignment.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Remove-EntraBetaUserExtension.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Remove-EntraBetaUserManager.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Set-EntraBetaUser.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Set-EntraBetaUserExtension.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Set-EntraBetaUserLicense.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Set-EntraBetaUserManager.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Set-EntraBetaUserThumbnailPhoto.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/Update-EntraBetaSignedInUserPassword.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraUserAppRoleAssignment.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraUserDirectReport.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraUserExtension.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraUserLicenseDetail.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraUserManager.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraUserMembership.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraUserOAuth2PermissionGrant.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Get-EntraUserOwnedObject.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraUser.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/New-EntraUserAppRoleAssignment.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Remove-EntraUser.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Remove-EntraUserAppRoleAssignment.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Remove-EntraUserExtension.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Remove-EntraUserManager.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Set-EntraUser.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Set-EntraUserExtension.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Set-EntraUserLicense.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Set-EntraUserManager.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Set-EntraUserThumbnailPhoto.md
  module/docs/entra-powershell-v1.0/Microsoft.Graph.Entra/Update-EntraSignedInUserPassword.md
Labels: Ready For Review, P0

#1275 Update New-EntraBetaPrivateAccessApplicationSegment.md
  module/docs/entra-powershell-beta/Microsoft.Graph.Entra.Beta/New-EntraBetaPrivateAccessApplicationSegment.md
Labels: Ready For Review, P0

#1294 Hotfix - Get-EntraGroup - Add example for -Property
  module/docs/entra-powershell-beta/Groups/Get-EntraBetaGroup.md
  module/docs/entra-powershell-v1.0/Groups/Get-EntraGroup.md
Labels: Ready For Review, P0

#1289 [Modularize] Enhancement - New-EntraServicePrincipalPasswordCredential to include displayName property
  module/Entra/Microsoft.Entra/Applications/New-EntraServicePrincipalPasswordCredential.ps1
  module/EntraBeta/Microsoft.Entra.Beta/Applications/New-EntraBetaServicePrincipalPasswordCredential.ps1
  module/docs/entra-powershell-beta/Applications/New-EntraBetaServicePrincipalPasswordCredential.md
  module/docs/entra-powershell-v1.0/Applications/New-EntraServicePrincipalPasswordCredential.md
  test/Entra/Applications/New-EntraServicePrincipalPasswordCredential.Tests.ps1
  test/EntraBeta/Applications/New-EntraBetaServicePrincipalPasswordCredential.Tests.ps1
Labels: Ready For Review, P1

#1301 Fix Get-EntraContext and Get-EntraBetaContext
  module/Entra/Microsoft.Entra/Authentication/Get-EntraContext.ps1
  module/EntraBeta/Microsoft.Entra.Beta/Authentication/Get-EntraContext.ps1
Labels: Ready For Review, P0

#1308 [Enhancements] Get-EntraDirectoryObjectOnPremisesProvisioningError
  module/Entra/Microsoft.Entra/DirectoryManagement/Get-EntraDirectoryObjectOnPremisesProvisioningError.ps1
  module/EntraBeta/Microsoft.Entra.Beta/DirectoryManagement/Get-EntraBetaDirectoryObjectOnPremisesProvisioningError.ps1
  module/docs/entra-powershell-beta/DirectoryManagement/Get-EntraBetaDirectoryObjectOnPremisesProvisioningError.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Get-EntraDirectoryObjectOnPremisesProvisioningError.md
  test/Entra/DirectoryManagement/Get-EntraDirectoryObjectOnPremisesProvisioningError.Tests.ps1
  test/EntraBeta/DirectoryManagement/Get-EntraBetaDirectoryObjectOnPremisesProvisioningError.Tests.ps1
Labels: Ready For Review, P0

#1314 Enganga/add enable entra docs
  module/Entra/Microsoft.Entra/Groups/Enable-EntraAzureADAlias.ps1
  module/Entra/Microsoft.Entra/SignIns/Enable-EntraAzureADAlias.ps1
  module/Entra/Microsoft.Entra/Users/Enable-EntraAzureADAlias.ps1
  module/docs/entra-powershell-beta/Applications/Enable-EntraAzureADAlias.md
  module/docs/entra-powershell-beta/Authentication/Enable-EntraAzureADAlias.md
  module/docs/entra-powershell-beta/DirectoryManagement/Enable-EntraAzureADAlias.md
  module/docs/entra-powershell-beta/Governance/Enable-EntraAzureADAlias.md
  module/docs/entra-powershell-beta/Groups/Enable-EntraAzureADAlias.md
  module/docs/entra-powershell-beta/NetworkAccess/Enable-EntraAzureADAlias.md
  module/docs/entra-powershell-beta/Reports/Enable-EntraAzureADAlias.md
  module/docs/entra-powershell-beta/SignIns/Enable-EntraAzureADAlias.md
  module/docs/entra-powershell-beta/Users/Enable-EntraAzureADAlias.md
  module/docs/entra-powershell-v1.0/Applications/Enable-EntraAzureADAlias.md
  module/docs/entra-powershell-v1.0/Authentication/Enable-EntraAzureADAlias.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Enable-EntraAzureADAlias.md
  module/docs/entra-powershell-v1.0/Governance/Enable-EntraAzureADAlias.md
  module/docs/entra-powershell-v1.0/Groups/Enable-EntraAzureADAlias.md
  module/docs/entra-powershell-v1.0/Reports/Enable-EntraAzureADAlias.md
  module/docs/entra-powershell-v1.0/SignIns/Enable-EntraAzureADAlias.md
  module/docs/entra-powershell-v1.0/Users/Enable-EntraAzureADAlias.md
Labels: Ready For Review, P0

#1315 [Modularize] Enrich examples to boost example quality KPI - Batch 2 (users)
  module/docs/entra-powershell-beta/Users/Get-EntraBetaUserAppRoleAssignment.md
  module/docs/entra-powershell-beta/Users/Get-EntraBetaUserDirectReport.md
  module/docs/entra-powershell-beta/Users/Get-EntraBetaUserExtension.md
  module/docs/entra-powershell-beta/Users/Get-EntraBetaUserLicenseDetail.md
  module/docs/entra-powershell-beta/Users/Get-EntraBetaUserManager.md
  module/docs/entra-powershell-beta/Users/Get-EntraBetaUserMembership.md
  module/docs/entra-powershell-beta/Users/Get-EntraBetaUserOwnedObject.md
  module/docs/entra-powershell-beta/Users/New-EntraBetaUser.md
  module/docs/entra-powershell-beta/Users/New-EntraBetaUserAppRoleAssignment.md
  module/docs/entra-powershell-beta/Users/Remove-EntraBetaUser.md
  module/docs/entra-powershell-beta/Users/Remove-EntraBetaUserAppRoleAssignment.md
  module/docs/entra-powershell-beta/Users/Remove-EntraBetaUserExtension.md
  module/docs/entra-powershell-beta/Users/Remove-EntraBetaUserManager.md
  module/docs/entra-powershell-beta/Users/Set-EntraBetaUser.md
  module/docs/entra-powershell-beta/Users/Set-EntraBetaUserExtension.md
  module/docs/entra-powershell-beta/Users/Set-EntraBetaUserLicense.md
  module/docs/entra-powershell-beta/Users/Set-EntraBetaUserManager.md
  module/docs/entra-powershell-beta/Users/Set-EntraBetaUserThumbnailPhoto.md
  module/docs/entra-powershell-beta/Users/Update-EntraBetaSignedInUserPassword.md
  module/docs/entra-powershell-v1.0/Users/Get-EntraUserAppRoleAssignment.md
  module/docs/entra-powershell-v1.0/Users/Get-EntraUserDirectReport.md
  module/docs/entra-powershell-v1.0/Users/Get-EntraUserExtension.md
  module/docs/entra-powershell-v1.0/Users/Get-EntraUserLicenseDetail.md
  module/docs/entra-powershell-v1.0/Users/Get-EntraUserManager.md
  module/docs/entra-powershell-v1.0/Users/Get-EntraUserMembership.md
  module/docs/entra-powershell-v1.0/Users/Get-EntraUserOAuth2PermissionGrant.md
  module/docs/entra-powershell-v1.0/Users/Get-EntraUserOwnedObject.md
  module/docs/entra-powershell-v1.0/Users/New-EntraUser.md
  module/docs/entra-powershell-v1.0/Users/New-EntraUserAppRoleAssignment.md
  module/docs/entra-powershell-v1.0/Users/Remove-EntraUser.md
  module/docs/entra-powershell-v1.0/Users/Remove-EntraUserAppRoleAssignment.md
  module/docs/entra-powershell-v1.0/Users/Remove-EntraUserExtension.md
  module/docs/entra-powershell-v1.0/Users/Remove-EntraUserManager.md
  module/docs/entra-powershell-v1.0/Users/Set-EntraUser.md
  module/docs/entra-powershell-v1.0/Users/Set-EntraUserExtension.md
  module/docs/entra-powershell-v1.0/Users/Set-EntraUserLicense.md
  module/docs/entra-powershell-v1.0/Users/Set-EntraUserManager.md
  module/docs/entra-powershell-v1.0/Users/Set-EntraUserThumbnailPhoto.md
  module/docs/entra-powershell-v1.0/Users/Update-EntraSignedInUserPassword.md
Labels: Ready For Review, P0

#1317 Enrich examples to boost example quality KPI - Batch 2 (Contacts, Custom security attributes)
  module/docs/entra-powershell-beta/DirectoryManagement/Add-EntraBetaCustomSecurityAttributeDefinitionAllowedValue.md
  module/docs/entra-powershell-beta/DirectoryManagement/Get-EntraBetaContact.md
  module/docs/entra-powershell-beta/DirectoryManagement/Get-EntraBetaContactDirectReport.md
  module/docs/entra-powershell-beta/DirectoryManagement/Get-EntraBetaContactManager.md
  module/docs/entra-powershell-beta/DirectoryManagement/Get-EntraBetaContactMembership.md
  module/docs/entra-powershell-beta/DirectoryManagement/Get-EntraBetaCustomSecurityAttributeDefinitionAllowedValue.md
  module/docs/entra-powershell-beta/DirectoryManagement/New-EntraBetaAttributeSet.md
  module/docs/entra-powershell-beta/DirectoryManagement/New-EntraBetaCustomSecurityAttributeDefinition.md
  module/docs/entra-powershell-beta/DirectoryManagement/Remove-EntraBetaContact.md
  module/docs/entra-powershell-beta/DirectoryManagement/Set-EntraBetaAttributeSet.md
  module/docs/entra-powershell-beta/DirectoryManagement/Set-EntraBetaCustomSecurityAttributeDefinition.md
  module/docs/entra-powershell-beta/DirectoryManagement/Set-EntraBetaCustomSecurityAttributeDefinitionAllowedValue.md
  module/docs/entra-powershell-v1.0/Authentication/Add-EntraEnvironment.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Add-EntraCustomSecurityAttributeDefinitionAllowedValue.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Get-EntraContact.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Get-EntraContactDirectReport.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Get-EntraContactManager.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Get-EntraContactMembership.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Get-EntraCustomSecurityAttributeDefinition.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Get-EntraCustomSecurityAttributeDefinitionAllowedValue.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/New-EntraAttributeSet.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/New-EntraCustomSecurityAttributeDefinition.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Remove-EntraContact.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Set-EntraAttributeSet.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Set-EntraCustomSecurityAttributeDefinition.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Set-EntraCustomSecurityAttributeDefinitionAllowedValue.md
Labels: Ready For Review, P0

#1313 [Modularize] Enrich examples to boost example quality KPI - Batch 3 [devices]
  module/docs/entra-powershell-beta/DirectoryManagement/Add-EntraBetaDeviceRegisteredOwner.md
  module/docs/entra-powershell-beta/DirectoryManagement/Add-EntraBetaDeviceRegisteredUser.md
  module/docs/entra-powershell-beta/DirectoryManagement/Get-EntraBetaDevice.md
  module/docs/entra-powershell-beta/DirectoryManagement/Get-EntraBetaDeviceRegisteredOwner.md
  module/docs/entra-powershell-beta/DirectoryManagement/Get-EntraBetaDeviceRegisteredUser.md
  module/docs/entra-powershell-beta/DirectoryManagement/New-EntraBetaDevice.md
  module/docs/entra-powershell-beta/DirectoryManagement/Remove-EntraBetaDevice.md
  module/docs/entra-powershell-beta/DirectoryManagement/Remove-EntraBetaDeviceRegisteredOwner.md
  module/docs/entra-powershell-beta/DirectoryManagement/Remove-EntraBetaDeviceRegisteredUser.md
  module/docs/entra-powershell-beta/DirectoryManagement/Set-EntraBetaDevice.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Add-EntraDeviceRegisteredOwner.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Add-EntraDeviceRegisteredUser.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Get-EntraDevice.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Get-EntraDeviceRegisteredOwner.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Get-EntraDeviceRegisteredUser.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/New-EntraDevice.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Remove-EntraDevice.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Remove-EntraDeviceRegisteredOwner.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Remove-EntraDeviceRegisteredUser.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Set-EntraDevice.md
Labels: Ready For Review, P0

#1312 [Modularize] Enrich examples to boost example quality KPI - Batch 5 [domains]
  module/docs/entra-powershell-beta/DirectoryManagement/Get-EntraBetaDomainNameReference.md
  module/docs/entra-powershell-beta/DirectoryManagement/Get-EntraBetaDomainServiceConfigurationRecord.md
  module/docs/entra-powershell-beta/DirectoryManagement/Get-EntraBetaDomainVerificationDnsRecord.md
  module/docs/entra-powershell-beta/DirectoryManagement/Get-EntraBetaPasswordPolicy.md
  module/docs/entra-powershell-beta/DirectoryManagement/New-EntraBetaDomain.md
  module/docs/entra-powershell-beta/DirectoryManagement/Remove-EntraBetaDomain.md
  module/docs/entra-powershell-beta/DirectoryManagement/Set-EntraBetaDomainFederationSettings.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Get-CrossCloudVerificationCode.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Get-EntraDomainNameReference.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Get-EntraDomainServiceConfigurationRecord.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Get-EntraDomainVerificationDnsRecord.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Get-EntraPasswordPolicy.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/New-EntraDomain.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Remove-EntraDomain.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Set-EntraDomainFederationSettings.md
Labels: Ready For Review, P0

#1305 fix Get-EntraDirectoryObjectOnPremisesProvisioningError
  module/Entra/Microsoft.Entra/DirectoryManagement/Get-EntraDirectoryObjectOnPremisesProvisioningError.ps1
  module/EntraBeta/Microsoft.Entra.Beta/DirectoryManagement/Get-EntraBetaDirectoryObjectOnPremisesProvisioningError.ps1
  module/docs/entra-powershell-beta/DirectoryManagement/Get-EntraBetaDirectoryObjectOnPremisesProvisioningError.md
  module/docs/entra-powershell-v1.0/DirectoryManagement/Get-EntraDirectoryObjectOnPremisesProvisioningError.md
  test/Entra/DirectoryManagement/Get-EntraDirectoryObjectOnPremisesProvisioningError.Tests.ps1
  test/EntraBeta/DirectoryManagement/Get-EntraBetaDirectoryObjectOnPremisesProvisioningError.Tests.ps1
Labels: Ready For Review, P0

#1320 [Modularize] Improvements to use ExecutionContext automatic variables
  module/Entra/Microsoft.Entra/Applications/New-EntraCustomHeaders.ps1
  module/Entra/Microsoft.Entra/Authentication/Get-EntraContext.ps1
  module/Entra/Microsoft.Entra/Authentication/New-EntraCustomHeaders.ps1
  module/Entra/Microsoft.Entra/DirectoryManagement/New-EntraCustomHeaders.ps1
  module/Entra/Microsoft.Entra/Governance/New-EntraCustomHeaders.ps1
  module/Entra/Microsoft.Entra/Groups/New-EntraCustomHeaders.ps1
  module/Entra/Microsoft.Entra/Reports/New-EntraCustomHeaders.ps1
  module/Entra/Microsoft.Entra/SignIns/New-EntraCustomHeaders.ps1
  module/Entra/Microsoft.Entra/Users/New-EntraCustomHeaders.ps1
  module/EntraBeta/Microsoft.Entra.Beta/Applications/New-EntraBetaCustomHeaders.ps1
  module/EntraBeta/Microsoft.Entra.Beta/Authentication/Get-EntraContext.ps1
  module/EntraBeta/Microsoft.Entra.Beta/Authentication/New-EntraBetaCustomHeaders.ps1
  module/EntraBeta/Microsoft.Entra.Beta/DirectoryManagement/New-EntraBetaCustomHeaders.ps1
  module/EntraBeta/Microsoft.Entra.Beta/Governance/New-EntraBetaCustomHeaders.ps1
  module/EntraBeta/Microsoft.Entra.Beta/Groups/New-EntraBetaCustomHeaders.ps1
  module/EntraBeta/Microsoft.Entra.Beta/NetworkAccess/New-EntraBetaCustomHeaders.ps1
  module/EntraBeta/Microsoft.Entra.Beta/Reports/New-EntraBetaCustomHeaders.ps1
  module/EntraBeta/Microsoft.Entra.Beta/SignIns/New-EntraBetaCustomHeaders.ps1
  module/EntraBeta/Microsoft.Entra.Beta/Users/New-EntraBetaCustomHeaders.ps1
Labels: Ready For Review, P0

#1310 [Modularize] Example improvements - SignIns category
  module/docs/entra-powershell-beta/SignIns/Get-EntraBetaAuthorizationPolicy.md
  module/docs/entra-powershell-beta/SignIns/Get-EntraBetaConditionalAccessPolicy.md
  module/docs/entra-powershell-beta/SignIns/Get-EntraBetaFeatureRolloutPolicy.md
  module/docs/entra-powershell-beta/SignIns/Get-EntraBetaNamedLocationPolicy.md
  module/docs/entra-powershell-beta/SignIns/Get-EntraBetaPermissionGrantConditionSet.md
  module/docs/entra-powershell-beta/SignIns/Get-EntraBetaPolicy.md
  module/docs/entra-powershell-beta/SignIns/New-EntraBetaConditionalAccessPolicy.md
  module/docs/entra-powershell-beta/SignIns/New-EntraBetaFeatureRolloutPolicy.md
  module/docs/entra-powershell-beta/SignIns/New-EntraBetaNamedLocationPolicy.md
  module/docs/entra-powershell-beta/SignIns/New-EntraBetaOauth2PermissionGrant.md
  module/docs/entra-powershell-beta/SignIns/New-EntraBetaPermissionGrantConditionSet.md
  module/docs/entra-powershell-beta/SignIns/New-EntraBetaPermissionGrantPolicy.md
  module/docs/entra-powershell-beta/SignIns/New-EntraBetaPolicy.md
  module/docs/entra-powershell-beta/SignIns/Remove-EntraBetaConditionalAccessPolicy.md
  module/docs/entra-powershell-beta/SignIns/Remove-EntraBetaFeatureRolloutPolicy.md
  module/docs/entra-powershell-beta/SignIns/Remove-EntraBetaNamedLocationPolicy.md
  module/docs/entra-powershell-beta/SignIns/Remove-EntraBetaPermissionGrantConditionSet.md
  module/docs/entra-powershell-beta/SignIns/Remove-EntraBetaPolicy.md
  module/docs/entra-powershell-beta/SignIns/Set-EntraBetaAuthorizationPolicy.md
  module/docs/entra-powershell-beta/SignIns/Set-EntraBetaConditionalAccessPolicy.md
  module/docs/entra-powershell-beta/SignIns/Set-EntraBetaFeatureRolloutPolicy.md
  module/docs/entra-powershell-beta/SignIns/Set-EntraBetaNamedLocationPolicy.md
  module/docs/entra-powershell-beta/SignIns/Set-EntraBetaPermissionGrantConditionSet.md
  module/docs/entra-powershell-beta/SignIns/Set-EntraBetaPermissionGrantPolicy.md
  module/docs/entra-powershell-beta/SignIns/Set-EntraBetaPolicy.md
  module/docs/entra-powershell-v1.0/SignIns/Get-EntraAuthorizationPolicy.md
  module/docs/entra-powershell-v1.0/SignIns/Get-EntraConditionalAccessPolicy.md
  module/docs/entra-powershell-v1.0/SignIns/Get-EntraFeatureRolloutPolicy.md
  module/docs/entra-powershell-v1.0/SignIns/Get-EntraNamedLocationPolicy.md
  module/docs/entra-powershell-v1.0/SignIns/Get-EntraPermissionGrantConditionSet.md
  module/docs/entra-powershell-v1.0/SignIns/Get-EntraPolicy.md
  module/docs/entra-powershell-v1.0/SignIns/New-EntraConditionalAccessPolicy.md
  module/docs/entra-powershell-v1.0/SignIns/New-EntraFeatureRolloutPolicy.md
  module/docs/entra-powershell-v1.0/SignIns/New-EntraNamedLocationPolicy.md
  module/docs/entra-powershell-v1.0/SignIns/New-EntraOauth2PermissionGrant.md
  module/docs/entra-powershell-v1.0/SignIns/New-EntraPermissionGrantConditionSet.md
  module/docs/entra-powershell-v1.0/SignIns/New-EntraPermissionGrantPolicy.md
  module/docs/entra-powershell-v1.0/SignIns/New-EntraPolicy.md
  module/docs/entra-powershell-v1.0/SignIns/Remove-EntraConditionalAccessPolicy.md
  module/docs/entra-powershell-v1.0/SignIns/Remove-EntraFeatureRolloutPolicy.md
  module/docs/entra-powershell-v1.0/SignIns/Remove-EntraNamedLocationPolicy.md
  module/docs/entra-powershell-v1.0/SignIns/Remove-EntraPermissionGrantConditionSet.md
  module/docs/entra-powershell-v1.0/SignIns/Remove-EntraPolicy.md
  module/docs/entra-powershell-v1.0/SignIns/Set-EntraAuthorizationPolicy.md
  module/docs/entra-powershell-v1.0/SignIns/Set-EntraConditionalAccessPolicy.md
  module/docs/entra-powershell-v1.0/SignIns/Set-EntraFeatureRolloutPolicy.md
  module/docs/entra-powershell-v1.0/SignIns/Set-EntraNamedLocationPolicy.md
  module/docs/entra-powershell-v1.0/SignIns/Set-EntraPermissionGrantConditionSet.md
  module/docs/entra-powershell-v1.0/SignIns/Set-EntraPermissionGrantPolicy.md
  module/docs/entra-powershell-v1.0/SignIns/Set-EntraPolicy.md
Labels: Ready For Review, P0

#1321 GA Initial Release v1.0.0
  module/Entra/config/ModuleMetadata.json
  module/EntraBeta/config/ModuleMetadata.json
Labels: Ready For Review, P0

#1327 Bug fix: Return UserPrincipalName for Get-EntraDirectoryObjectOnPremisesProvisioningError command
  module/Entra/Microsoft.Entra/DirectoryManagement/Get-EntraDirectoryObjectOnPremisesProvisioningError.ps1
  module/EntraBeta/Microsoft.Entra.Beta/DirectoryManagement/Get-EntraBetaDirectoryObjectOnPremisesProvisioningError.ps1
Labels: Ready For Review, P0
